
# @name create-user
GET http://localhost:3000/user

###
# @name create-user
POST http://localhost:3333/user/create
Content-Type: application/json

{
     
  "nome": "string",
  "sobrenome": "string",
  "senha": "string",
  "email": "20201063@isptec.co.ao"
}
###
POST http://localhost:3000/Album
Content-Type: application/json

{
     
     "id_user": "2"
}
###
POST http://localhost:3000/Album/getBySet
Content-Type: application/json

{
     
     "albums": ["2","1"]
}
###
POST http://localhost:3000/user/getByName
Content-Type: application/json

{
 
     "email":"t"
}


###

# @name edit-user
POST http://localhost:3333/user/editUser/1
Content-Type: application/json

{
      "name":"Tesa",
     "password": "passwordHash",
     "email":"s@gmail.com"
} 

###

# @name edit-user
POST http://localhost:3333/user/getById/1
Content-Type: application/json

{ 
     "id": 1 
}
###

# @name create-authentication
POST  http://localhost:3000/create
Content-Type: application/json

{ 
    "refreshToken" : "ya29.a0AfB_byAifDMP_AvgeeYZWpLsb_9eJOZqxxoTWvDxBVxsKSqhg7EMh-l-1X_u0E68rro-EOPmbPNPUydV6tpcVOHQ_ZOKGYy7bteX6oDrzhjs4d07LPFOzVikVRLF0ArXUKQDqQ-ebglpYxkNddLt-SnXI7cEFeAycPbEaCgYKAcESARMSFQHGX2Mi_sEdUnYy7ALHR2CCo_-vlw0171", 
    "name": "psPhotos_"
} 
###

# @name create-authentication
POST  http://localhost:3000/album/createAlbum
Content-Type: application/json

{
              "idAlbum": "response.data.data.id",
              "nameAlbum": "response.data.data.name",
              "webViewLink": "response.data.data.webViewLink",
              "id_user":"1"

} 